sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"

notifications:
  email:
    on_success: always
    on_failure: always
