sudo: false
language: c
 
addons:
  apt:
    packages:
    - pandoc
 
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh -L -w 13784 | bash
 
branches:
  only:
  - master
  #- /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email:
    on_failure: always
    on_success: never