sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc
    
branches:
  only:
  - master
  #~ - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script: 
  - curl -sO https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
  - bash release.sh -p trade-filter -w 13784 -g 7.3.0

notifications:
  email:
    on_success: always
    on_failure: always
