sudo: false
language: minimal
 
beforescript: curl -sSO https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
script: bash release.sh
 
branches:
  only:
  - master
  #- /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email:
    on_failure: always
    on_success: never