sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc
    
branches:
  only:
  - master
  #~ - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh -p 16408 | bash

notifications:
  email:
    on_success: always
    on_failure: always
