sudo: false

language: c

addons:
  apt:
    packages:
    - pandoc
    - luarocks

branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"

script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
