sudo: false
language: bash

addons:
  apt:
    packages:
    - luarocks
    - pandoc

before_script:
- luarocks install --local luacheck
- PATH=$HOME/.luarocks/bin:$PATH
- eval $(luarocks path --bin)

script:
- luacheck .

before_deploy:
- lua .release/libstrip
- lua .release/changelog > CHANGELOG.md
- curl -s https://raw.githubusercontent.com/Rainrider/packager/wowace/release.sh -o .release/release.sh

deploy:
  provider: script
  script: bash .release/release.sh -- -L
  skip_cleanup: true
  on:
    tags: true
    condition: '"$TRAVIS_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$'

notifications:
  email:
    on_failure: always
    on_success: never
