sudo: false
language: minimal

addons:
  apt:
    packages:
    - luarocks

install:
  - luarocks install --local luacheck
  
before_script:
  - /home/travis/.luarocks/bin/luacheck . --no-color -q

script:
  #- /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_failure: always
    on_success: never