name: Release new AddOn no-lib version
on:
  push:
    branches:
      - master
    tags:
      #- '**'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # pull the repository (required)
      - uses: actions/checkout@v1

      # run release.sh with arguments
      - uses: BigWigsMods/packager@master
        with:
          args: release.sh -s

      # use a specific version of release.sh (short-SHA)
      #- uses: BigWigsMods/packager@9a689b3
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GH_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
